# Mapping from Rapier rustdoc item paths to MoonBit symbols.
#
# Purpose:
# - Rapier pub surface is audited from rustdoc JSON for rapier2d/rapier3d v0.32.0
#   (default features only).
# - MoonBit export surface is audited from */pkg.generated.mbti and */spec.mbt.
# - API names do NOT need to match. This file lets us declare equivalences so the
#   audit can focus on remaining semantic gaps.
#
# Notes:
# - Keys MUST be quoted (they contain ::).
# - Values are either a single quoted string or an array of quoted strings.
# - Symbols are free-form, but we recommend: "<moonbit package>::<Type>::<method>"
#
# Examples:
# [map]
# "rapier2d::pipeline::PhysicsPipeline::step" = "Milky2018/moon_rapier/pipeline::PhysicsPipeline::step"
# "rapier3d::prelude::RigidBodySet" = [
#   "Milky2018/moon_rapier/dynamics::RigidBodySet3D",
#   "Milky2018/moon_rapier/dynamics::RigidBodySet3DReal",
# ]
#
# For items we explicitly do not want to track (e.g. Rust ecosystem re-exports),
# list them under [ignore] with a short reason string.

[map]

"rapier2d::VERSION" = "Milky2018/moon_rapier/core::RAPIER_REFERENCE_VERSION"
"rapier3d::VERSION" = "Milky2018/moon_rapier/core::RAPIER_REFERENCE_VERSION"

"rapier2d::math::SPATIAL_DIM" = "Milky2018/moon_rapier/core::SPATIAL_DIM2"
"rapier2d::math::ANG_DIM" = "Milky2018/moon_rapier/core::ANG_DIM2"
"rapier2d::math::MAX_MANIFOLD_POINTS" = "Milky2018/moon_rapier/core::MAX_MANIFOLD_POINTS2"

"rapier3d::math::SPATIAL_DIM" = "Milky2018/moon_rapier/core::SPATIAL_DIM3"
"rapier3d::math::ANG_DIM" = "Milky2018/moon_rapier/core::ANG_DIM3"
"rapier3d::math::MAX_MANIFOLD_POINTS" = "Milky2018/moon_rapier/core::MAX_MANIFOLD_POINTS3"

"rapier2d::math::Dim" = "Milky2018/moon_rapier/core::Dim2"
"rapier2d::math::AngDim" = "Milky2018/moon_rapier/core::AngDim2"
"rapier3d::math::Dim" = "Milky2018/moon_rapier/core::Dim3"
"rapier3d::math::AngDim" = "Milky2018/moon_rapier/core::AngDim3"

"rapier2d::math::DMatrix" = "Milky2018/moon_rapier/core::DMatrix"
"rapier3d::math::DMatrix" = "Milky2018/moon_rapier/core::DMatrix"
"rapier2d::math::JacobianView" = "Milky2018/moon_rapier/core::DMatrix"
"rapier2d::math::JacobianViewMut" = "Milky2018/moon_rapier/core::DMatrix"
"rapier3d::math::JacobianView" = "Milky2018/moon_rapier/core::DMatrix"
"rapier3d::math::JacobianViewMut" = "Milky2018/moon_rapier/core::DMatrix"

"rapier2d::math::SimdVector" = "Milky2018/moon_rapier/core::Vec2"
"rapier2d::math::SimdPoint" = "Milky2018/moon_rapier/core::Vec2"
"rapier2d::math::SimdPose" = "Milky2018/moon_rapier/core::Isometry2"
"rapier2d::math::SimdRotation" = "Milky2018/moon_rapier/core::Rot2"
"rapier2d::math::SimdAngVector" = "Milky2018/moon_rapier/core::Real"
"rapier2d::math::SimdAngularInertia" = "Milky2018/moon_rapier/core::Real"
"rapier2d::math::SimdMatrix" = "Milky2018/moon_rapier/core::Mat2"
"rapier2d::math::TangentImpulse" = "Milky2018/moon_rapier/core::TangentImpulse2"

"rapier3d::math::SimdVector" = "Milky2018/moon_rapier/core::Vec3"
"rapier3d::math::SimdPoint" = "Milky2018/moon_rapier/core::Vec3"
"rapier3d::math::SimdPose" = "Milky2018/moon_rapier/core::Isometry3"
"rapier3d::math::SimdRotation" = "Milky2018/moon_rapier/core::Quat"
"rapier3d::math::SimdAngVector" = "Milky2018/moon_rapier/core::Vec3"
"rapier3d::math::SimdAngularInertia" = "Milky2018/moon_rapier/core::SdpMat3"
"rapier3d::math::SimdMatrix" = "Milky2018/moon_rapier/core::Mat3"
"rapier3d::math::TangentImpulse" = "Milky2018/moon_rapier/core::TangentImpulse3"

"rapier2d::counters::Counters::custom_time" = "Milky2018/moon_rapier/counters::Counters::custom_time_ms"
"rapier3d::counters::Counters::custom_time" = "Milky2018/moon_rapier/counters::Counters::custom_time_ms"
"rapier2d::counters::timer::Timer::resume" = "Milky2018/moon_rapier/counters::Timer::resume_timer"
"rapier3d::counters::timer::Timer::resume" = "Milky2018/moon_rapier/counters::Timer::resume_timer"
"rapier2d::counters::timer::Timer::time" = "Milky2018/moon_rapier/counters::Timer::time_ms"
"rapier3d::counters::timer::Timer::time" = "Milky2018/moon_rapier/counters::Timer::time_ms"

"rapier2d::control::character_controller::EffectiveCharacterMovement" = "Milky2018/moon_rapier/control::EffectiveMovement"
"rapier3d::control::character_controller::EffectiveCharacterMovement" = "Milky2018/moon_rapier/control::EffectiveMovement3DReal"
"rapier3d::control::ray_cast_vehicle_controller::DynamicRayCastVehicleController::wheels_mut" = "Milky2018/moon_rapier/control::DynamicRayCastVehicleController3DReal::wheels"

"rapier2d::utils::DIM_MINUS_ONE" = "Milky2018/moon_rapier/utils::DIM_MINUS_ONE2"
"rapier3d::utils::DIM_MINUS_ONE" = "Milky2018/moon_rapier/utils::DIM_MINUS_ONE3"

"rapier2d::utils::try_normalize_and_get_length" = "Milky2018/moon_rapier/utils::try_normalize_and_get_length2"
"rapier3d::utils::try_normalize_and_get_length" = "Milky2018/moon_rapier/utils::try_normalize_and_get_length3"

"rapier2d::utils::angular_inertia_ops::AngularInertiaOps" = "Milky2018/moon_rapier/utils::AngularInertiaOps"
"rapier3d::utils::angular_inertia_ops::AngularInertiaOps" = "Milky2018/moon_rapier/utils::AngularInertiaOps"
"rapier2d::utils::angular_inertia_ops::AngularInertiaOps::AngVector" = "Milky2018/moon_rapier/utils::AngularInertiaOpsAngVector2"
"rapier2d::utils::angular_inertia_ops::AngularInertiaOps::AngMatrix" = "Milky2018/moon_rapier/utils::AngularInertiaOpsAngMatrix2"
"rapier3d::utils::angular_inertia_ops::AngularInertiaOps::AngVector" = "Milky2018/moon_rapier/utils::AngularInertiaOpsAngVector3"
"rapier3d::utils::angular_inertia_ops::AngularInertiaOps::AngMatrix" = "Milky2018/moon_rapier/utils::AngularInertiaOpsAngMatrix3"
"rapier2d::utils::angular_inertia_ops::AngularInertiaOps::transform_vector" = "Milky2018/moon_rapier/utils::angular_inertia_transform_vector2"
"rapier2d::utils::angular_inertia_ops::AngularInertiaOps::into_matrix" = "Milky2018/moon_rapier/utils::angular_inertia_into_matrix2"
"rapier3d::utils::angular_inertia_ops::AngularInertiaOps::transform_vector" = "Milky2018/moon_rapier/utils::angular_inertia_transform_vector3"
"rapier3d::utils::angular_inertia_ops::AngularInertiaOps::into_matrix" = "Milky2018/moon_rapier/utils::angular_inertia_into_matrix3"

"rapier2d::utils::component_mul::ComponentMul" = "Milky2018/moon_rapier/utils::ComponentMul"
"rapier3d::utils::component_mul::ComponentMul" = "Milky2018/moon_rapier/utils::ComponentMul"
"rapier2d::utils::component_mul::ComponentMul::component_mul" = "Milky2018/moon_rapier/utils::component_mul2"
"rapier3d::utils::component_mul::ComponentMul::component_mul" = "Milky2018/moon_rapier/utils::component_mul3"

"rapier2d::utils::copysign::CopySign" = "Milky2018/moon_rapier/utils::CopySign"
"rapier3d::utils::copysign::CopySign" = "Milky2018/moon_rapier/utils::CopySign"
"rapier2d::utils::copysign::CopySign::copy_sign_to" = "Milky2018/moon_rapier/utils::copy_sign_to"
"rapier3d::utils::copysign::CopySign::copy_sign_to" = "Milky2018/moon_rapier/utils::copy_sign_to"

"rapier2d::utils::cross_product::CrossProduct" = "Milky2018/moon_rapier/utils::CrossProduct"
"rapier3d::utils::cross_product::CrossProduct" = "Milky2018/moon_rapier/utils::CrossProduct"
"rapier2d::utils::cross_product::CrossProduct::Result" = "Milky2018/moon_rapier/utils::CrossProductResult2"
"rapier3d::utils::cross_product::CrossProduct::Result" = "Milky2018/moon_rapier/utils::CrossProductResult3"
"rapier2d::utils::cross_product::CrossProduct::gcross" = "Milky2018/moon_rapier/core::Vec2::cross"
"rapier3d::utils::cross_product::CrossProduct::gcross" = "Milky2018/moon_rapier/core::Vec3::cross"

"rapier2d::utils::cross_product_matrix::CrossProductMatrix" = "Milky2018/moon_rapier/utils::CrossProductMatrix"
"rapier3d::utils::cross_product_matrix::CrossProductMatrix" = "Milky2018/moon_rapier/utils::CrossProductMatrix"
"rapier2d::utils::cross_product_matrix::CrossProductMatrix::CrossMat" = "Milky2018/moon_rapier/utils::CrossProductMatrixCrossMat2"
"rapier2d::utils::cross_product_matrix::CrossProductMatrix::CrossMatTr" = "Milky2018/moon_rapier/utils::CrossProductMatrixCrossMatTr2"
"rapier3d::utils::cross_product_matrix::CrossProductMatrix::CrossMat" = "Milky2018/moon_rapier/utils::CrossProductMatrixCrossMat3"
"rapier3d::utils::cross_product_matrix::CrossProductMatrix::CrossMatTr" = "Milky2018/moon_rapier/utils::CrossProductMatrixCrossMatTr3"
"rapier2d::utils::cross_product_matrix::CrossProductMatrix::gcross_matrix" = "Milky2018/moon_rapier/utils::gcross_matrix2"
"rapier2d::utils::cross_product_matrix::CrossProductMatrix::gcross_matrix_tr" = "Milky2018/moon_rapier/utils::gcross_matrix_tr2"
"rapier3d::utils::cross_product_matrix::CrossProductMatrix::gcross_matrix" = "Milky2018/moon_rapier/utils::gcross_matrix3"

"rapier2d::pipeline::event_handler::ActiveEvents::COLLISION_EVENTS" = "Milky2018/moon_rapier/collision::ActiveEvents::collision_events"
"rapier2d::pipeline::event_handler::ActiveEvents::CONTACT_FORCE_EVENTS" = "Milky2018/moon_rapier/collision::ActiveEvents::contact_force_events"
"rapier3d::pipeline::event_handler::ActiveEvents::COLLISION_EVENTS" = "Milky2018/moon_rapier/collision::ActiveEvents::collision_events"
"rapier3d::pipeline::event_handler::ActiveEvents::CONTACT_FORCE_EVENTS" = "Milky2018/moon_rapier/collision::ActiveEvents::contact_force_events"

"rapier2d::pipeline::physics_hooks::ActiveHooks::FILTER_CONTACT_PAIRS" = "Milky2018/moon_rapier/collision::ActiveHooks::filter_contact_pairs"
"rapier2d::pipeline::physics_hooks::ActiveHooks::FILTER_INTERSECTION_PAIR" = "Milky2018/moon_rapier/collision::ActiveHooks::filter_intersection_pair"
"rapier2d::pipeline::physics_hooks::ActiveHooks::MODIFY_SOLVER_CONTACTS" = "Milky2018/moon_rapier/collision::ActiveHooks::modify_solver_contacts"
"rapier3d::pipeline::physics_hooks::ActiveHooks::FILTER_CONTACT_PAIRS" = "Milky2018/moon_rapier/collision::ActiveHooks::filter_contact_pairs"
"rapier3d::pipeline::physics_hooks::ActiveHooks::FILTER_INTERSECTION_PAIR" = "Milky2018/moon_rapier/collision::ActiveHooks::filter_intersection_pair"
"rapier3d::pipeline::physics_hooks::ActiveHooks::MODIFY_SOLVER_CONTACTS" = "Milky2018/moon_rapier/collision::ActiveHooks::modify_solver_contacts"

"rapier2d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_FIXED" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_fixed"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_KINEMATIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_kinematic"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_DYNAMIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_dynamic"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_SENSORS" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_sensors"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_SOLIDS" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_solids"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::ONLY_DYNAMIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::only_dynamic"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::ONLY_KINEMATIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::only_kinematic"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::ONLY_FIXED" = "Milky2018/moon_rapier/collision::QueryFilterFlags::only_fixed"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_FIXED" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_fixed"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_KINEMATIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_kinematic"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_DYNAMIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_dynamic"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_SENSORS" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_sensors"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::EXCLUDE_SOLIDS" = "Milky2018/moon_rapier/collision::QueryFilterFlags::exclude_solids"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::ONLY_DYNAMIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::only_dynamic"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::ONLY_KINEMATIC" = "Milky2018/moon_rapier/collision::QueryFilterFlags::only_kinematic"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::ONLY_FIXED" = "Milky2018/moon_rapier/collision::QueryFilterFlags::only_fixed"

"rapier2d::pipeline::query_pipeline::QueryFilter::test" = "Milky2018/moon_rapier/collision::QueryFilter::passes"
"rapier2d::pipeline::query_pipeline::QueryFilterFlags::test" = "Milky2018/moon_rapier/collision::QueryFilterFlags::passes"
"rapier3d::pipeline::query_pipeline::QueryFilter::test" = "Milky2018/moon_rapier/collision::QueryFilter::passes"
"rapier3d::pipeline::query_pipeline::QueryFilterFlags::test" = "Milky2018/moon_rapier/collision::QueryFilterFlags::passes"
"rapier3d::utils::cross_product_matrix::CrossProductMatrix::gcross_matrix_tr" = "Milky2018/moon_rapier/utils::gcross_matrix_tr3"

"rapier2d::utils::dot_product::DotProduct" = "Milky2018/moon_rapier/utils::DotProduct"
"rapier3d::utils::dot_product::DotProduct" = "Milky2018/moon_rapier/utils::DotProduct"
"rapier2d::utils::dot_product::DotProduct::Result" = "Milky2018/moon_rapier/utils::DotProductResult"
"rapier3d::utils::dot_product::DotProduct::Result" = "Milky2018/moon_rapier/utils::DotProductResult"
"rapier2d::utils::dot_product::DotProduct::gdot" = "Milky2018/moon_rapier/core::Vec2::dot"
"rapier3d::utils::dot_product::DotProduct::gdot" = "Milky2018/moon_rapier/core::Vec3::dot"
"rapier2d::utils::dot_product::SimdLength" = "Milky2018/moon_rapier/utils::SimdLength"
"rapier3d::utils::dot_product::SimdLength" = "Milky2018/moon_rapier/utils::SimdLength"
"rapier2d::utils::dot_product::SimdLength::simd_length" = "Milky2018/moon_rapier/core::Vec2::length"
"rapier3d::utils::dot_product::SimdLength::simd_length" = "Milky2018/moon_rapier/core::Vec3::length"

"rapier2d::utils::index_mut2::IndexMut2" = "Milky2018/moon_rapier/utils::IndexMut2"
"rapier3d::utils::index_mut2::IndexMut2" = "Milky2018/moon_rapier/utils::IndexMut2"
"rapier2d::utils::index_mut2::IndexMut2::index_mut2" = "Milky2018/moon_rapier/utils::index_mut2"
"rapier3d::utils::index_mut2::IndexMut2::index_mut2" = "Milky2018/moon_rapier/utils::index_mut2"
"rapier2d::utils::index_mut2::IndexMut2::index_mut_const" = "Milky2018/moon_rapier/utils::index_mut_const"
"rapier3d::utils::index_mut2::IndexMut2::index_mut_const" = "Milky2018/moon_rapier/utils::index_mut_const"

"rapier2d::utils::matrix_column::MatrixColumn" = "Milky2018/moon_rapier/utils::MatrixColumn"
"rapier3d::utils::matrix_column::MatrixColumn" = "Milky2018/moon_rapier/utils::MatrixColumn"
"rapier2d::utils::matrix_column::MatrixColumn::Column" = "Milky2018/moon_rapier/utils::MatrixColumnColumn2"
"rapier3d::utils::matrix_column::MatrixColumn::Column" = "Milky2018/moon_rapier/utils::MatrixColumnColumn3"
"rapier2d::utils::matrix_column::MatrixColumn::column" = "Milky2018/moon_rapier/utils::mat2_column"
"rapier3d::utils::matrix_column::MatrixColumn::column" = "Milky2018/moon_rapier/utils::mat3_column"

"rapier2d::utils::orthonormal_basis::OrthonormalBasis" = "Milky2018/moon_rapier/utils::OrthonormalBasis"
"rapier3d::utils::orthonormal_basis::OrthonormalBasis" = "Milky2018/moon_rapier/utils::OrthonormalBasis"
"rapier2d::utils::orthonormal_basis::OrthonormalBasis::Basis" = "Milky2018/moon_rapier/utils::OrthonormalBasisBasis2"
"rapier3d::utils::orthonormal_basis::OrthonormalBasis::Basis" = "Milky2018/moon_rapier/utils::OrthonormalBasisBasis3"
"rapier2d::utils::orthonormal_basis::OrthonormalBasis::orthonormal_basis" = "Milky2018/moon_rapier/utils::orthonormal_basis2"
"rapier3d::utils::orthonormal_basis::OrthonormalBasis::orthonormal_basis" = "Milky2018/moon_rapier/utils::orthonormal_basis3"
"rapier2d::utils::orthonormal_basis::OrthonormalBasis::orthonormal_vector" = "Milky2018/moon_rapier/utils::orthonormal_vector2"
"rapier3d::utils::orthonormal_basis::OrthonormalBasis::orthonormal_vector" = "Milky2018/moon_rapier/utils::orthonormal_vector3"

"rapier2d::utils::pos_ops::PoseOps" = "Milky2018/moon_rapier/utils::PoseOps"
"rapier3d::utils::pos_ops::PoseOps" = "Milky2018/moon_rapier/utils::PoseOps"
"rapier2d::utils::pos_ops::PoseOps::append_translation" = "Milky2018/moon_rapier/utils::pose_append_translation2"
"rapier2d::utils::pos_ops::PoseOps::prepend_translation" = "Milky2018/moon_rapier/utils::pose_prepend_translation2"
"rapier2d::utils::pos_ops::PoseOps::append_rotation" = "Milky2018/moon_rapier/utils::pose_append_rotation2"
"rapier2d::utils::pos_ops::PoseOps::prepend_rotation" = "Milky2018/moon_rapier/utils::pose_prepend_rotation2"
"rapier3d::utils::pos_ops::PoseOps::append_translation" = "Milky2018/moon_rapier/utils::pose_append_translation3"
"rapier3d::utils::pos_ops::PoseOps::prepend_translation" = "Milky2018/moon_rapier/utils::pose_prepend_translation3"
"rapier3d::utils::pos_ops::PoseOps::append_rotation" = "Milky2018/moon_rapier/utils::pose_append_rotation3"
"rapier3d::utils::pos_ops::PoseOps::prepend_rotation" = "Milky2018/moon_rapier/utils::pose_prepend_rotation3"

"rapier2d::utils::rotation_ops::RotationOps" = "Milky2018/moon_rapier/utils::RotationOps"
"rapier3d::utils::rotation_ops::RotationOps" = "Milky2018/moon_rapier/utils::RotationOps"
"rapier2d::utils::rotation_ops::RotationOps::to_mat" = "Milky2018/moon_rapier/utils::rot2_to_mat"
"rapier3d::utils::rotation_ops::RotationOps::to_mat" = "Milky2018/moon_rapier/core::Quat::to_mat3"
"rapier3d::utils::rotation_ops::RotationOps::diff_conj1_2" = "Milky2018/moon_rapier/utils::quat_diff_conj1_2"
"rapier3d::utils::rotation_ops::RotationOps::diff_conj1_2_tr" = "Milky2018/moon_rapier/utils::quat_diff_conj1_2_tr"
"rapier3d::utils::rotation_ops::RotationOps::mul_assign_unchecked" = "Milky2018/moon_rapier/utils::quat_mul_assign_unchecked"

"rapier2d::utils::scalar_type::ScalarType" = "Milky2018/moon_rapier/utils::ScalarType"
"rapier3d::utils::scalar_type::ScalarType" = "Milky2018/moon_rapier/utils::ScalarType"
"rapier2d::utils::scalar_type::ScalarType::Pose" = "Milky2018/moon_rapier/utils::ScalarTypePose2"
"rapier3d::utils::scalar_type::ScalarType::Pose" = "Milky2018/moon_rapier/utils::ScalarTypePose3"
"rapier2d::utils::scalar_type::ScalarType::Vector" = "Milky2018/moon_rapier/utils::ScalarTypeVector2"
"rapier3d::utils::scalar_type::ScalarType::Vector" = "Milky2018/moon_rapier/utils::ScalarTypeVector3"
"rapier2d::utils::scalar_type::ScalarType::Rotation" = "Milky2018/moon_rapier/utils::ScalarTypeRotation2"
"rapier3d::utils::scalar_type::ScalarType::Rotation" = "Milky2018/moon_rapier/utils::ScalarTypeRotation3"
"rapier2d::utils::scalar_type::ScalarType::Matrix" = "Milky2018/moon_rapier/utils::ScalarTypeMatrix2"
"rapier3d::utils::scalar_type::ScalarType::Matrix" = "Milky2018/moon_rapier/utils::ScalarTypeMatrix3"
"rapier2d::utils::scalar_type::ScalarType::AngVector" = "Milky2018/moon_rapier/utils::ScalarTypeAngVector2"
"rapier3d::utils::scalar_type::ScalarType::AngVector" = "Milky2018/moon_rapier/utils::ScalarTypeAngVector3"
"rapier2d::utils::scalar_type::ScalarType::AngInertia" = "Milky2018/moon_rapier/utils::ScalarTypeAngInertia2"
"rapier3d::utils::scalar_type::ScalarType::AngInertia" = "Milky2018/moon_rapier/utils::ScalarTypeAngInertia3"

"rapier2d::utils::simd_real_copy::SimdRealCopy" = "Milky2018/moon_rapier/utils::SimdRealCopy"
"rapier3d::utils::simd_real_copy::SimdRealCopy" = "Milky2018/moon_rapier/utils::SimdRealCopy"

"rapier2d::utils::simd_select::SimdSelect" = "Milky2018/moon_rapier/utils::SimdSelect"
"rapier3d::utils::simd_select::SimdSelect" = "Milky2018/moon_rapier/utils::SimdSelect"
"rapier2d::utils::simd_select::SimdSelect::select" = "Milky2018/moon_rapier/utils::select_vec2"
"rapier3d::utils::simd_select::SimdSelect::select" = "Milky2018/moon_rapier/utils::select_vec3"

[ignore]
